import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { calculatePassage, validatePassageInput } from "@/features/passagePlanning/calculations"; import { useProgress } from "@/hooks/useProgress"; import { TOPIC_IDS } from "@/constants/topicRegistry";
const scenarios=[{name:"Harbour hop",distanceNm:18,speedKnots:6,fuelLitresPerHour:2},{name:"Channel crossing",distanceNm:72,speedKnots:7,fuelLitresPerHour:3.5}];
export function FuelCalculator(){
 const [values,setValues]=useState({distanceNm:18,speedKnots:6,fuelLitresPerHour:2,reservePercent:20,departureTime:""}); const {saveProgress}=useProgress();
 const errors=validatePassageInput(values); const result=useMemo(()=>errors.length?null:calculatePassage(values),[values,errors.length]);
 const field=(key:keyof typeof values,label:string,type="number")=><div><Label htmlFor={key}>{label}</Label><Input id={key} type={type} min="0" value={values[key]} onChange={e=>setValues(v=>({...v,[key]:type==="number"?Number(e.target.value):e.target.value}))}/></div>;
 return <div className="space-y-5"><div className="flex flex-wrap gap-2">{scenarios.map(s=><Button variant="outline" key={s.name} onClick={()=>setValues(v=>({...v,...s}))}>{s.name}</Button>)}</div><div className="grid sm:grid-cols-2 gap-4">{field("distanceNm","Distance (nm)")}{field("speedKnots","SOG (knots)")}{field("fuelLitresPerHour","Fuel rate (litres/hour)")}{field("reservePercent","Reserve (%)")}{field("departureTime","Departure time","datetime-local")}</div>{errors.map(e=><p role="alert" className="text-destructive" key={e}>{e}</p>)}{result&&<Card aria-live="polite"><CardHeader><CardTitle>Plan result</CardTitle></CardHeader><CardContent className="grid sm:grid-cols-2 gap-2"><p>Passage time: <b>{result.hours.toFixed(2)} h</b></p><p>Fuel: <b>{result.fuelLitres.toFixed(1)} L</b></p><p>With reserve: <b>{result.fuelWithReserveLitres.toFixed(1)} L</b></p><p>ETA: <b>{result.eta?new Date(result.eta).toLocaleString():"Choose departure"}</b></p></CardContent></Card>}<Button disabled={!result} onClick={()=>void saveProgress(TOPIC_IDS.PASSAGE_PLANNING_CALCULATOR,true,100,10,{input:values})}>Complete calculation</Button></div>
}
