import { useState } from "react";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { calculatePassage, formatDuration, formatEta, possibleInstants, validatePassageInput, type PassageCalculation } from "@/features/passagePlanning/calculations"; import { useProgress } from "@/hooks/useProgress"; import { TOPIC_IDS } from "@/constants/topicRegistry";

const scenarios=[
 {name:"Harbour hop — motor",description:"18 nm motor passage; 6 kn expected SOG; engine runs 3 h at 2 L/h; 2 L for manoeuvring/holding; 20% planning reserve; 20 L usable.",distanceNm:18,speedKnots:6,engineHours:3,fuelLitresPerHour:2,additionalFuelLitres:2,reservePercent:20,usableFuelLitres:20,evidence:"Motor vessel: log/sea-trial evidence at passage RPM and expected load; forecast tide and weather checked.",reserveBasis:"20% exercise allowance; skipper must replace it using route alternatives, delay/diversion exposure and vessel/operator policy.",departureTime:""},
 {name:"Channel crossing — sail/auxiliary",description:"72 nm sailing passage; 6 kn expected SOG; 4 h auxiliary engine at 3.5 L/h; 6 L for charging, harbour work and delay; 30% planning reserve; 45 L usable.",distanceNm:72,speedKnots:6,engineHours:4,fuelLitresPerHour:3.5,additionalFuelLitres:6,reservePercent:30,usableFuelLitres:45,evidence:"Sailing yacht with auxiliary: conservative SOG from tidal plan and forecast; measured consumption at expected RPM, load and sea state.",reserveBasis:"30% exercise allowance for delay/diversion; replace with a passage-specific amount under vessel/operator and applicable policy.",departureTime:""},
] as const;
type Values={distanceNm:number;speedKnots:number;engineHours:number;fuelLitresPerHour:number;additionalFuelLitres:number;reservePercent:number;usableFuelLitres:number;evidence:string;reserveBasis:string;departureTime:string};
const initial:Values={...scenarios[0]};

export function FuelCalculator(){
 const [values,setValues]=useState<Values>(initial); const [result,setResult]=useState<PassageCalculation|null>(null); const [submitted,setSubmitted]=useState(values); const [departureInstant,setDepartureInstant]=useState(""); const {saveProgress}=useProgress();
 const errors=[...validatePassageInput(values),...(!values.evidence.trim()?["Record the vessel-specific speed and fuel-rate evidence."]:[]),...(!values.reserveBasis.trim()?["Record why the reserve suits this passage."]:[])];
 const timeZone=Intl.DateTimeFormat().resolvedOptions().timeZone; const instants=values.departureTime?possibleInstants(values.departureTime,timeZone):[];
 const update=(next:Values)=>{setValues(next);setResult(null);setDepartureInstant("");};
 const field=(key:keyof Values,label:string,type="number")=><div><Label htmlFor={key}>{label}</Label><Input id={key} type={type} min="0" value={values[key]} onChange={e=>update({...values,[key]:type==="number"?Number(e.target.value):e.target.value})}/></div>;
 const calculate=()=>{if(errors.length||values.departureTime&&(instants.length!==1&&!departureInstant))return; const input={...values,departureTime:departureInstant||instants[0]};setSubmitted({...values,departureTime:input.departureTime||""});setResult(calculatePassage(input));};
 return <div className="space-y-5">
  <Card><CardHeader><CardTitle>Scope: small-craft diesel passage estimate</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p>This teaching tool estimates elapsed time from one whole-passage average <b>speed over ground (SOG)</b>, and diesel from separately entered engine-running hours. It is not a route, tidal-stream, tank-gauge or fuel-quality calculator.</p><p>Build SOG from leg distances, speed through water, forecast tide/current and expected weather. Use conservative vessel records or sea trials for fuel rate at the intended RPM, displacement, loading and conditions; allow for sea state, wind and fouling. Recalculate by leg outside this tool where those assumptions vary.</p><p>“Usable fuel” excludes tank contents that cannot reliably reach the engine, including unusable heel and allowances for contamination. Confirm tank limits physically. Include manoeuvring, idling, heating, charging/generator use, holding, delay and diversion in engine hours or additional consumption.</p></CardContent></Card>
  <div className="space-y-2"><p className="font-medium">Worked example presets (applying one replaces every field, including reserve evidence and departure)</p>{scenarios.map(s=><div key={s.name}><Button variant="outline" onClick={()=>update({...s})}>{s.name}</Button><p className="text-sm text-muted-foreground">{s.description}</p></div>)}</div>
  <div className="grid sm:grid-cols-2 gap-4">{field("distanceNm","Route distance (nautical miles)")}{field("speedKnots","Conservative passage SOG (knots)")}{field("engineHours","Engine-running duration (hours)")}{field("fuelLitresPerHour","Vessel fuel rate at planned load (litres/hour)")}{field("additionalFuelLitres","Extra consumption: delay, diversion and other loads (litres)")}{field("reservePercent","Passage-specific reserve (%)")}{field("usableFuelLitres","Usable fuel aboard (litres)")}{field("departureTime",`Departure date and time (${timeZone})`,"datetime-local")}</div>
  <div><Label htmlFor="evidence">Speed/fuel-rate evidence and expected conditions</Label><Input id="evidence" value={values.evidence} onChange={e=>update({...values,evidence:e.target.value})}/></div>
  <div><Label htmlFor="reserveBasis">Reserve basis: changes, alternatives and policy</Label><Input id="reserveBasis" value={values.reserveBasis} onChange={e=>update({...values,reserveBasis:e.target.value})}/><p className="text-sm text-muted-foreground">There is no universal safe percentage. Carry enough for the planned journey plus an adequate reserve if plans change, chosen for the scenario, vessel, alternatives and applicable rules/operator policy.</p></div>
  {errors.map(e=><p role="alert" className="text-destructive" key={e}>{e}</p>)}{values.departureTime&&instants.length===0&&<p role="alert">That local time does not exist because of a daylight-saving clock change. Choose another time.</p>}{instants.length===2&&<div><Label htmlFor="departure-offset">This time occurs twice; choose the intended offset</Label><select id="departure-offset" value={departureInstant} onChange={e=>{setDepartureInstant(e.target.value);setResult(null)}}><option value="">Choose an occurrence</option>{instants.map(instant=><option value={instant} key={instant}>{formatEta(instant,"en-GB",timeZone)}</option>)}</select></div>}
  {!result&&<p role="status">Inputs changed. Calculate to produce an updated result.</p>}<Button disabled={errors.length>0||!!values.departureTime&&(instants.length===0||instants.length===2&&!departureInstant)} onClick={calculate}>Calculate / update result</Button>
  {result&&<Card aria-live="polite"><CardHeader><CardTitle>Calculated plan</CardTitle></CardHeader><CardContent className="space-y-2"><p>Passage duration: {submitted.distanceNm} nm ÷ {submitted.speedKnots} kn SOG = <b>{formatDuration(result.durationMinutes)}</b> ({result.hours.toFixed(4)} h). This is elapsed time, not engine time; minutes round to nearest.</p><p>Engine fuel: {submitted.engineHours} h × {submitted.fuelLitresPerHour} L/h = <b>{result.fuelLitres.toFixed(4)} L</b>.</p><p>Computed subtotal: {result.fuelLitres.toFixed(4)} L + {submitted.additionalFuelLitres} L extra = <b>{result.subtotalFuelLitres.toFixed(4)} L</b>.</p><p>Reserve: {result.subtotalFuelLitres.toFixed(4)} L × {submitted.reservePercent}% = <b>{result.reserveLitres.toFixed(4)} L</b>. Basis: {submitted.reserveBasis}</p><p>Total: <b>{result.fuelWithReserveLitres.toFixed(4)} L</b>; practical carry <b>{result.practicalFuelLitres} L</b> (rounded up).</p><p role={result.hasEnoughUsableFuel?undefined:"alert"}>Usable-fuel check: {submitted.usableFuelLitres} L aboard − {result.practicalFuelLitres} L required = <b>{result.usableFuelMarginLitres} L</b>. {result.hasEnoughUsableFuel?"The entered usable amount covers this estimate.":"INSUFFICIENT: change the plan; indicated tank quantity does not make this safe."}</p><p>Evidence: {submitted.evidence}</p><p>ETA: <b>{result.eta?formatEta(result.eta):"Choose a departure time"}</b>.</p><p className="font-medium">Before departure, verify the route leg by leg, current forecasts, actual usable clean fuel, engine condition and realistic alternatives. This arithmetic does not establish that a passage is safe.</p></CardContent></Card>}
  <Button disabled={!result||!result.hasEnoughUsableFuel} onClick={()=>void saveProgress(TOPIC_IDS.PASSAGE_PLANNING_CALCULATOR,true,100,10,{input:submitted})}>Complete calculation</Button>
 </div>;
}
