import { useState } from "react";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { calculatePassage, formatDuration, formatEta, possibleInstants, validatePassageInput, type PassageCalculation } from "@/features/passagePlanning/calculations"; import { useProgress } from "@/hooks/useProgress"; import { TOPIC_IDS } from "@/constants/topicRegistry";
const scenarios=[{name:"Harbour hop",distanceNm:18,speedKnots:6,fuelLitresPerHour:2},{name:"Channel crossing",distanceNm:72,speedKnots:7,fuelLitresPerHour:3.5}];
export function FuelCalculator(){
 const [values,setValues]=useState({distanceNm:18,speedKnots:6,fuelLitresPerHour:2,reservePercent:20,departureTime:""}); const [result,setResult]=useState<PassageCalculation|null>(null); const [submitted,setSubmitted]=useState(values); const [departureInstant,setDepartureInstant]=useState(""); const {saveProgress}=useProgress();
 const errors=validatePassageInput(values);
 const timeZone=Intl.DateTimeFormat().resolvedOptions().timeZone; const instants=values.departureTime?possibleInstants(values.departureTime,timeZone):[];
 const update=(next:typeof values)=>{setValues(next);setResult(null);setDepartureInstant("");};
 const field=(key:keyof typeof values,label:string,type="number")=><div><Label htmlFor={key}>{label}</Label><Input id={key} type={type} min="0" value={values[key]} onChange={e=>update({...values,[key]:type==="number"?Number(e.target.value):e.target.value})}/></div>;
 const calculate=()=>{ if(errors.length||values.departureTime&&(instants.length!==1&&!departureInstant))return; const input={...values,departureTime:departureInstant||instants[0]}; setSubmitted(values); setResult(calculatePassage(input)); };
 return <div className="space-y-5"><div className="flex flex-wrap gap-2">{scenarios.map(s=><Button variant="outline" key={s.name} onClick={()=>update({...values,...s})}>{s.name}</Button>)}</div><div className="grid sm:grid-cols-2 gap-4">{field("distanceNm","Distance (nautical miles)")}{field("speedKnots","Speed over ground (knots)")}{field("fuelLitresPerHour","Fuel consumption (litres/hour)")}{field("reservePercent","Reserve (%)")}{field("departureTime",`Departure date and time (${timeZone})`,"datetime-local")}</div>{errors.map(e=><p role="alert" className="text-destructive" key={e}>{e}</p>)}{values.departureTime&&instants.length===0&&<p role="alert">That local time does not exist because of a daylight-saving clock change. Choose another time.</p>}{instants.length===2&&<div><Label htmlFor="departure-offset">This time occurs twice; choose the intended offset</Label><select id="departure-offset" value={departureInstant} onChange={e=>{setDepartureInstant(e.target.value);setResult(null)}}><option value="">Choose an occurrence</option>{instants.map(instant=><option value={instant} key={instant}>{formatEta(instant,"en-GB",timeZone)}</option>)}</select></div>}{!result&&<p role="status">Inputs changed. Calculate to produce an updated result.</p>}<Button disabled={errors.length>0||!!values.departureTime&&(instants.length===0||instants.length===2&&!departureInstant)} onClick={calculate}>Calculate / update result</Button>{result&&<Card aria-live="polite"><CardHeader><CardTitle>Calculated plan</CardTitle></CardHeader><CardContent className="space-y-2"><p>Time: {submitted.distanceNm} nm ÷ {submitted.speedKnots} kn = <b>{formatDuration(result.durationMinutes)}</b> ({result.hours.toFixed(4)} decimal hours). Minutes are rounded to the nearest minute.</p><p>Base fuel (unrounded): {submitted.distanceNm} ÷ {submitted.speedKnots} × {submitted.fuelLitresPerHour} = <b>{result.fuelLitres.toFixed(4)} L</b>.</p><p>Reserve (unrounded): {result.fuelLitres.toFixed(4)} L × {submitted.reservePercent}% = <b>{result.reserveLitres.toFixed(4)} L</b>.</p><p>Exact estimated total (displayed to 4 decimals): <b>{result.fuelWithReserveLitres.toFixed(4)} L</b>. Conservative practical carry: <b>{result.practicalFuelLitres} L</b> (rounded up to the next whole litre; never down). Confirm tank capacity, usable fuel and vessel limits separately.</p><p>ETA: <b>{result.eta?formatEta(result.eta):"Choose a departure time"}</b>. The timezone and UTC offset are explicit; the calculated instant is preserved across locale and daylight-saving changes.</p></CardContent></Card>}<Button disabled={!result} onClick={()=>void saveProgress(TOPIC_IDS.PASSAGE_PLANNING_CALCULATOR,true,100,10,{input:submitted})}>Complete calculation</Button></div>
}
