import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { PassagePlanBuilder } from "@/components/passagePlanning/PassagePlanBuilder";
import { makePassagePlanRecord, PASSAGE_PLAN_CACHE_VERSION, type PassagePlan } from "./passagePlan";

const loadProgress=vi.fn(),saveProgress=vi.fn(),loadProgressDetailed=vi.fn(),saveProgressDetailed=vi.fn();
vi.mock("@/hooks/useProgress",()=>({useProgress:()=>({loadProgress,saveProgress,loadProgressDetailed,saveProgressDetailed})}));
let currentUserId="user-a";
vi.mock("@/contexts/AuthHooks",()=>({useAuth:()=>({user:currentUserId?{id:currentUserId}:null})}));

const plan=(name="Local draft"):PassagePlan=>{const recent=new Date(Date.now()-60_000).toISOString(),future=new Date(Date.now()+3_600_000).toISOString();return{version:PASSAGE_PLAN_CACHE_VERSION,name,departure:future,speed:5,coordinateFormat:"degrees-decimal-minutes",datum:"WGS84",coordinatePrecision:"0.1 minute",safety:{departureBerth:"start",destinationBerth:"finish",limits:"limits",abortDecision:"abort",alternatives:"divert",manualVerification:"Current route checked against chart and notices"},provenance:{weather:"Met Office issue: 1000 validity: 24 hours",tide:"Admiralty tide table edition: 2026",chart:"Chart No. 3418 edition: 2026 correction status checked",publications:"Almanac edition: 2026",preparedAt:recent,revisedAt:recent},points:[{id:"1",name:"Start",latitude:"50°00.0'N",longitude:"001°00.0'W",inboundLeg:null},{id:"2",name:"Finish",latitude:"50°03.0'N",longitude:"001°00.0'W",inboundLeg:{course:20,distanceNm:3,notes:"",tidalGate:"",weatherWindow:""}}]}};
const acknowledge=()=>{fireEvent.click(screen.getByLabelText(/I independently checked this current route/));fireEvent.click(screen.getByLabelText(/Source freshness policy/))};

describe("passage plan production persistence contract",()=>{
 beforeEach(()=>{vi.restoreAllMocks();currentUserId="user-a";localStorage.clear();sessionStorage.clear();loadProgress.mockReset().mockResolvedValue(null);saveProgress.mockReset().mockResolvedValue(true);loadProgressDetailed.mockReset().mockResolvedValue({status:"missing",record:null});saveProgressDetailed.mockReset().mockResolvedValue("remote")});
 it("retains a revision-10 remote head and persists explicit conflict resolution after edits during hydration",async()=>{let resolve!:(value:unknown)=>void;loadProgressDetailed.mockImplementation(()=>new Promise(done=>{resolve=done}));localStorage.setItem("day-skipper-passage-plan:user-a",JSON.stringify(makePassagePlanRecord(plan(),"user-a")));render(<PassagePlanBuilder/>);expect((screen.getByLabelText("Plan name") as HTMLInputElement).value).toBe("Local draft");fireEvent.change(screen.getByLabelText("Plan name"),{target:{value:"Edit during load"}});const remote={...makePassagePlanRecord(plan("Remote"),"user-a"),revision:10};await act(async()=>resolve({status:"remote",record:{answers_history:{passagePlanRecord:remote}}}));expect((screen.getByLabelText("Plan name") as HTMLInputElement).value).toBe("Edit during load");expect(screen.getByRole("status").textContent).toContain("preserved");fireEvent.click(screen.getByRole("button",{name:"Keep local draft"}));const resolved=JSON.parse(localStorage.getItem("day-skipper-passage-plan:user-a")!);expect(resolved).toMatchObject({revision:12,ownerId:"user-a",plan:{name:"Edit during load"}})});
 it("keeps dirty navigation protection and reports an actionable failure when local saving throws",async()=>{render(<PassagePlanBuilder/>);await waitFor(()=>expect(screen.getByRole("status").textContent).not.toContain("Loading"));const setItemSpy=vi.spyOn(localStorage,"setItem").mockImplementation(()=>{throw new DOMException("full","QuotaExceededError")});fireEvent.change(screen.getByLabelText("Plan name"),{target:{value:"Unsaved"}});await waitFor(()=>expect(screen.getByRole("status").textContent).toContain("Local draft save failed"),{timeout:1500});setItemSpy.mockRestore();const event=new Event("beforeunload",{cancelable:true});window.dispatchEvent(event);expect(event.defaultPrevented).toBe(true)});
 it("does not advance an unchanged completed draft revision",async()=>{const completed={...makePassagePlanRecord(plan(),"user-a",null,"2026-08-11T10:00:00Z"),completedRevision:1,completionStatus:"confirmed" as const};localStorage.setItem("day-skipper-passage-plan:user-a",JSON.stringify(completed));render(<PassagePlanBuilder/>);await waitFor(()=>expect((screen.getByRole("button",{name:"Save draft"}) as HTMLButtonElement).disabled).toBe(false));fireEvent.click(screen.getByRole("button",{name:"Save draft"}));await waitFor(()=>expect(screen.getByRole("status").textContent).toContain("synced remotely"));const stored=JSON.parse(localStorage.getItem("day-skipper-passage-plan:user-a")!);expect(stored).toMatchObject({revision:1,completedRevision:1,completionStatus:"confirmed"})});
 it("reloads a queued completion as queued rather than confirmed",()=>{const queued={...makePassagePlanRecord(plan(),"user-a"),completedRevision:1,completionStatus:"queued" as const};localStorage.setItem("day-skipper-passage-plan:user-a",JSON.stringify(queued));render(<PassagePlanBuilder/>);expect(screen.getByRole("status").textContent).toContain("Queued completion loaded");expect(screen.queryByText(/Confirmed completed plan loaded/)).toBeNull()});
 it.each([["false",false],["thrown",new Error("offline")]])("keeps detailed %s completion failures retryable",async(_label,outcome)=>{localStorage.setItem("day-skipper-passage-plan:user-a",JSON.stringify(makePassagePlanRecord(plan(),"user-a")));if(outcome instanceof Error)saveProgressDetailed.mockRejectedValueOnce(outcome);else saveProgressDetailed.mockResolvedValueOnce(outcome);render(<PassagePlanBuilder/>);await waitFor(()=>expect((screen.getByRole("button",{name:"Save & complete plan"}) as HTMLButtonElement).disabled).toBe(false));acknowledge();fireEvent.click(screen.getByRole("button",{name:"Save & complete plan"}));await waitFor(()=>expect(screen.getByRole("status").textContent).toMatch(/not persisted|failed/));expect(screen.getByRole("button",{name:"Retry save"})).toBeTruthy()});
 it("retries the confirmed marker rather than a pre-completion draft after its local write fails",async()=>{localStorage.setItem("day-skipper-passage-plan:user-a",JSON.stringify(makePassagePlanRecord(plan(),"user-a")));render(<PassagePlanBuilder/>);await waitFor(()=>expect((screen.getByRole("button",{name:"Save & complete plan"}) as HTMLButtonElement).disabled).toBe(false));acknowledge();const original=localStorage.setItem.bind(localStorage);let writes=0;const setItemSpy=vi.spyOn(localStorage,"setItem").mockImplementation((key,value)=>{writes+=1;if(writes===2)throw new DOMException("full","QuotaExceededError");return original(key,value)});fireEvent.click(screen.getByRole("button",{name:"Save & complete plan"}));await waitFor(()=>expect(screen.getByRole("status").textContent).toContain("confirmed result is retained"));setItemSpy.mockRestore();fireEvent.click(screen.getByRole("button",{name:"Retry save"}));expect(JSON.parse(localStorage.getItem("day-skipper-passage-plan:user-a")!)).toMatchObject({completedRevision:1,completionStatus:"confirmed"})});
 it("copies an anonymous draft explicitly without changing its source owner",()=>{const session="11111111-1111-4111-8111-111111111111",anonymousOwner=`anonymous:${session}`,anonymousKey=`day-skipper-passage-plan:${anonymousOwner}`;sessionStorage.setItem("day-skipper-passage-plan-anonymous-session",JSON.stringify(session));localStorage.setItem(anonymousKey,JSON.stringify(makePassagePlanRecord(plan("Anonymous"),anonymousOwner)));render(<PassagePlanBuilder/>);fireEvent.click(screen.getByRole("button",{name:"Copy anonymous draft to my account"}));expect(JSON.parse(localStorage.getItem("day-skipper-passage-plan:user-a")!)).toMatchObject({ownerId:"user-a",plan:{name:"Anonymous"}});expect(JSON.parse(localStorage.getItem(anonymousKey)!)).toMatchObject({ownerId:anonymousOwner})});
 it("ignores a delayed completion response after the owner boundary changes",async()=>{let release!:(value:"remote")=>void;saveProgressDetailed.mockImplementationOnce(()=>new Promise(done=>{release=done}));localStorage.setItem("day-skipper-passage-plan:user-a",JSON.stringify(makePassagePlanRecord(plan(),"user-a")));const view=render(<PassagePlanBuilder/>);await waitFor(()=>expect((screen.getByRole("button",{name:"Save & complete plan"}) as HTMLButtonElement).disabled).toBe(false));acknowledge();fireEvent.click(screen.getByRole("button",{name:"Save & complete plan"}));currentUserId="user-b";view.rerender(<PassagePlanBuilder/>);await act(async()=>release("remote"));expect(localStorage.getItem("day-skipper-passage-plan:user-b")).toBeNull();expect(screen.getByRole("status").textContent).not.toContain("completion persisted")});
 it("serializes rapid remote draft saves and leaves the newest revision authoritative",async()=>{let releaseFirst!:(value:"remote")=>void;saveProgressDetailed.mockImplementationOnce(()=>new Promise(done=>{releaseFirst=done})).mockResolvedValue("remote");render(<PassagePlanBuilder/>);await waitFor(()=>expect(screen.getByRole("status").textContent).not.toContain("Loading"));fireEvent.change(screen.getByLabelText("Plan name"),{target:{value:"first"}});await waitFor(()=>expect(saveProgressDetailed).toHaveBeenCalledTimes(1));fireEvent.change(screen.getByLabelText("Plan name"),{target:{value:"second"}});await act(async()=>releaseFirst("remote"));await waitFor(()=>expect(saveProgressDetailed).toHaveBeenCalledTimes(2),{timeout:1500});expect(saveProgressDetailed.mock.calls[1][4].passagePlanRecord.plan.name).toBe("second");await waitFor(()=>expect(screen.getByRole("status").textContent).toContain("synced remotely"))});
 it("turns a thrown hydration into an accessible retry state",async()=>{loadProgressDetailed.mockRejectedValueOnce(new Error("offline")).mockResolvedValueOnce({status:"missing",record:null});render(<PassagePlanBuilder/>);await waitFor(()=>expect(screen.getByRole("status").textContent).toContain("Remote loading failed"));fireEvent.click(screen.getByRole("button",{name:"Retry remote load"}));await waitFor(()=>expect(loadProgressDetailed).toHaveBeenCalledTimes(2));expect(screen.getByRole("status").textContent).toContain("No saved plan found")});
});
