import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { PassagePlanBuilder } from "@/components/passagePlanning/PassagePlanBuilder";
import { makePassagePlanRecord, PASSAGE_PLAN_CACHE_VERSION, type PassagePlan } from "./passagePlan";

const loadProgress=vi.fn(),saveProgress=vi.fn(),loadProgressDetailed=vi.fn(),saveProgressDetailed=vi.fn();
vi.mock("@/hooks/useProgress",()=>({useProgress:()=>({loadProgress,saveProgress,loadProgressDetailed,saveProgressDetailed})}));
vi.mock("@/contexts/AuthHooks",()=>({useAuth:()=>({user:{id:"user-a"}})}));

const plan=(name="Local draft"):PassagePlan=>{const recent=new Date(Date.now()-60_000).toISOString(),future=new Date(Date.now()+3_600_000).toISOString();return{version:PASSAGE_PLAN_CACHE_VERSION,name,departure:future,speed:5,coordinateFormat:"degrees-decimal-minutes",datum:"WGS84",coordinatePrecision:"0.1 minute",safety:{departureBerth:"start",destinationBerth:"finish",limits:"limits",abortDecision:"abort",alternatives:"divert",manualVerification:""},provenance:{weather:"Met Office issue: 1000 validity: 24 hours",tide:"Admiralty tide table edition: 2026",chart:"Chart No. 3418 edition: 2026 correction status checked",publications:"Almanac edition: 2026",preparedAt:recent,revisedAt:recent},points:[{id:"1",name:"Start",latitude:"50°00.0'N",longitude:"001°00.0'W",inboundLeg:null},{id:"2",name:"Finish",latitude:"50°03.0'N",longitude:"001°00.0'W",inboundLeg:{course:20,distanceNm:3,notes:"",tidalGate:"",weatherWindow:""}}]}};

describe("passage plan production persistence contract",()=>{
 beforeEach(()=>{localStorage.clear();sessionStorage.clear();loadProgress.mockReset().mockResolvedValue(null);saveProgress.mockReset().mockResolvedValue(true);loadProgressDetailed.mockReset().mockResolvedValue({status:"missing",record:null});saveProgressDetailed.mockReset().mockResolvedValue("remote")});
 it("renders the authenticated local draft immediately and preserves edits while hydration is slow",async()=>{let resolve!:(value:unknown)=>void;loadProgressDetailed.mockImplementation(()=>new Promise(done=>{resolve=done}));localStorage.setItem("day-skipper-passage-plan:user-a",JSON.stringify(makePassagePlanRecord(plan(),"user-a")));render(<PassagePlanBuilder/>);expect((screen.getByLabelText("Plan name") as HTMLInputElement).value).toBe("Local draft");fireEvent.change(screen.getByLabelText("Plan name"),{target:{value:"Edit during load"}});await act(async()=>resolve({status:"remote",record:{answers_history:{passagePlanRecord:makePassagePlanRecord(plan("Remote"),"user-a")}}}));expect((screen.getByLabelText("Plan name") as HTMLInputElement).value).toBe("Edit during load");expect(screen.getByRole("status").textContent).toContain("preserved")});
 it("keeps dirty navigation protection and reports an actionable failure when local saving throws",async()=>{render(<PassagePlanBuilder/>);await waitFor(()=>expect(loadProgressDetailed).toHaveBeenCalled());const original=Storage.prototype.setItem;vi.spyOn(Storage.prototype,"setItem").mockImplementation(()=>{throw new DOMException("full","QuotaExceededError")});fireEvent.change(screen.getByLabelText("Plan name"),{target:{value:"Unsaved"}});await waitFor(()=>expect(screen.getByText(/Local draft save failed/)).toBeTruthy(),{timeout:1500});const event=new Event("beforeunload",{cancelable:true});window.dispatchEvent(event);expect(event.defaultPrevented).toBe(true);Storage.prototype.setItem=original;vi.restoreAllMocks()});
 it("does not advance an unchanged completed draft revision",async()=>{const completed={...makePassagePlanRecord(plan(),"user-a",null,"2026-08-11T10:00:00Z"),completedRevision:1};localStorage.setItem("day-skipper-passage-plan:user-a",JSON.stringify(completed));render(<PassagePlanBuilder/>);fireEvent.click(screen.getByRole("button",{name:"Save draft"}));const stored=JSON.parse(localStorage.getItem("day-skipper-passage-plan:user-a")!);expect(stored).toMatchObject({revision:1,completedRevision:1});expect(screen.getByRole("status").textContent).toContain("completion revision was preserved")});
});
