import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type Mark = { colour: "white" | "red" | "green" | "yellow"; label: string };

const colourClass = { white: "bg-white border-slate-500", red: "bg-red-600 border-red-800", green: "bg-green-600 border-green-800", yellow: "bg-yellow-300 border-yellow-600" };

// Exported alongside the lesson so safety-critical range tests exercise the rendered source of truth.
// eslint-disable-next-line react-refresh/only-export-components
export const RULE_22_RANGES = [
  { length: "50 m or more", masthead: "6", side: "3", stern: "3", towing: "3", allRound: "3" },
  { length: "12 m to under 50 m", masthead: "5*", side: "2", stern: "2", towing: "2", allRound: "2" },
  { length: "Under 12 m", masthead: "2", side: "1", stern: "2", towing: "2", allRound: "2" },
] as const;

const LightMarks = ({ marks }: { marks: Mark[] }) => <span className="inline-flex flex-wrap items-center gap-1">{marks.map((mark, index) => <span key={`${mark.label}-${index}`} className="inline-flex items-center gap-1"><span aria-hidden="true" className={`h-4 w-4 rounded-full border-2 ${colourClass[mark.colour]}`} /><span>{mark.label}</span></span>)}</span>;

const LightPlan = ({ title, height, aspect, caption }: { title: string; height: Mark[][]; aspect: { port?: Mark[]; ahead?: Mark[]; starboard?: Mark[]; astern?: Mark[] }; caption: string }) => (
  <figure className="my-3 rounded-md border p-3 forced-colors:border-[CanvasText]">
    <p className="font-semibold">{title}</p>
    <div className="mt-2 grid gap-3 text-xs sm:grid-cols-2">
      <div><p className="font-medium">Side/height layout (highest first; labels state fore–aft position)</p><ol className="mt-1 list-decimal space-y-1 pl-5">{height.map((row, index) => <li key={index}><LightMarks marks={row} /></li>)}</ol></div>
      <div><p className="font-medium">Plan view: sectors by observer aspect</p><dl className="mt-1 grid grid-cols-[auto_1fr] gap-x-2 gap-y-1">{Object.entries(aspect).map(([side, marks]) => <div className="contents" key={side}><dt className="capitalize">{side}</dt><dd><LightMarks marks={marks} /></dd></div>)}</dl></div>
    </div>
    <figcaption className="text-xs text-muted-foreground"><strong>Structured equivalent:</strong> {caption}</figcaption>
  </figure>
);

const DredgingShapePlan = () => <figure className="my-3 rounded-md border p-3"><div className="grid grid-cols-3 items-center gap-3 text-center text-xs"><div><ShapeStack shapes={["ball","ball"]} caption="Obstructed side: two balls vertically." /></div><div><ShapeStack shapes={["ball","diamond","ball"]} caption="Centre/status: ball–diamond–ball vertically." /></div><div><ShapeStack shapes={["diamond","diamond"]} caption="Safe-passing side: two diamonds vertically." /></div></div><figcaption className="text-xs text-muted-foreground">Viewed across the vessel: obstruction indication and safe-passing indication are on their respective sides, in addition to the central RAM status shapes.</figcaption></figure>;

const ShapeStack = ({ shapes, caption }: { shapes: ("ball" | "diamond" | "cone-down" | "cone-up" | "cylinder")[]; caption: string }) => (
  <figure className="my-3 rounded-md border p-3 forced-colors:border-[CanvasText]">
    <div className="flex min-h-24 flex-col items-center justify-center gap-2 forced-colors:text-[CanvasText]" aria-hidden="true">
      {shapes.map((shape, index) => shape === "ball" ? <span key={index} className="h-6 w-6 rounded-full bg-foreground" /> : shape === "diamond" ? <span key={index} className="h-6 w-6 rotate-45 bg-foreground" /> : shape === "cylinder" ? <span key={index} className="h-9 w-5 bg-foreground" /> : shape === "cone-up" ? <span key={index} className="h-0 w-0 border-x-[12px] border-b-[24px] border-x-transparent border-b-foreground" /> : <span key={index} className="h-0 w-0 border-x-[12px] border-t-[24px] border-x-transparent border-t-foreground" />)}
    </div>
    <figcaption className="text-xs text-muted-foreground"><strong>Structured equivalent:</strong> {caption}</figcaption>
  </figure>
);

const Requirement = ({ children }: { children: React.ReactNode }) => <li><strong>Requirement:</strong> {children}</li>;

export const PartCLights = () => <div className="space-y-6">
  <Card id="rule-20" tabIndex={-1} className="scroll-mt-28 focus:outline-none"><CardHeader><CardTitle>Rules 20–22: when, what and how far</CardTitle></CardHeader><CardContent className="space-y-4 text-sm">
    <ul className="list-disc space-y-2 pl-5">
      <Requirement>Rules 20–31 apply in all weathers. Exhibit their lights from sunset to sunrise; during that period show no other lights that can be mistaken for, impair the visibility or distinctive character of, or interfere with keeping a proper lookout for the prescribed lights.</Requirement>
      <Requirement>Also exhibit the prescribed lights from sunrise to sunset in restricted visibility, and whenever else considered necessary. Shapes comply by day.</Requirement>
      <Requirement>Rule 21 defines a masthead light as white over 225° (ahead to 22.5° abaft each beam); sidelights as green to starboard and red to port, each 112.5°; sternlight as white over 135° astern; towing light as yellow with the sternlight's characteristics; all-round as 360°; flashing as 120 or more flashes per minute.</Requirement>
    </ul>
    <div className="overflow-x-auto"><table className="w-full min-w-[38rem] border-collapse text-left text-xs"><caption className="mb-2 text-left font-semibold">Rule 22 minimum visibility, nautical miles</caption><thead><tr>{["Vessel length", "Masthead", "Sidelight", "Sternlight", "Towing", "All-round"].map(h => <th className="border p-2" key={h}>{h}</th>)}</tr></thead><tbody>{RULE_22_RANGES.map(r => <tr key={r.length}><th className="border p-2">{r.length}</th><td className="border p-2">{r.masthead}</td><td className="border p-2">{r.side}</td><td className="border p-2">{r.stern}</td><td className="border p-2">{r.towing}</td><td className="border p-2">{r.allRound}</td></tr>)}</tbody></table></div>
    <p className="text-xs text-muted-foreground">* A vessel 12 m to under 20 m: masthead light 3 miles. For inconspicuous, partly submerged objects/tows, Rule 22(d) specifies 3 miles for all-round white lights.</p>
  </CardContent></Card>

  <div className="grid min-w-0 gap-6 md:grid-cols-2">
    <Card id="rule-23" tabIndex={-1} className="scroll-mt-28 focus:outline-none"><CardHeader><CardTitle>Rule 23: power-driven underway</CardTitle></CardHeader><CardContent className="text-sm"><LightPlan title="Power-driven vessel 50 m or more" height={[[{colour:"white",label:"aft masthead—higher and abaft"}],[{colour:"white",label:"forward masthead"}],[{colour:"red",label:"port sidelight"},{colour:"green",label:"starboard sidelight"}],[{colour:"white",label:"sternlight"}]]} aspect={{ahead:[{colour:"white",label:"masthead lights"},{colour:"red",label:"port"},{colour:"green",label:"starboard"}],port:[{colour:"white",label:"masthead lights"},{colour:"red",label:"port sidelight"}],starboard:[{colour:"white",label:"masthead lights"},{colour:"green",label:"starboard sidelight"}],astern:[{colour:"white",label:"sternlight"}]}} caption="Forward white masthead light; second white masthead light abaft and higher; red port and green starboard sidelights; white sternlight. Sector arcs determine which are visible from each aspect."/><ul className="list-disc space-y-2 pl-5"><Requirement>Under 50 m need not show the second masthead light, but may. At 50 m or more it is required.</Requirement><Requirement>Under 12 m may instead show an all-round white plus sidelights; under 7 m with maximum speed not over 7 knots may show an all-round white and, if practicable, sidelights. Where practicable, its all-round white/masthead light is forward of the sidelights.</Requirement><Requirement>Non-displacement air-cushion craft also flash all-round yellow; WIG craft taking off, landing or flying near the surface also flash high-intensity all-round red.</Requirement></ul></CardContent></Card>

    <Card id="rule-24" tabIndex={-1} className="scroll-mt-28 focus:outline-none"><CardHeader><CardTitle>Rule 24: towing and pushing</CardTitle></CardHeader><CardContent className="text-sm"><LightPlan title="Towing astern, tow 200 m or less" height={[[{colour:"white",label:"two masthead lights vertically"}],[{colour:"yellow",label:"towing light above sternlight"}],[{colour:"white",label:"sternlight"}]]} aspect={{ahead:[{colour:"white",label:"two masthead lights"},{colour:"red",label:"port"},{colour:"green",label:"starboard"}],port:[{colour:"white",label:"two masthead lights"},{colour:"red",label:"port sidelight"}],starboard:[{colour:"white",label:"two masthead lights"},{colour:"green",label:"starboard sidelight"}],astern:[{colour:"yellow",label:"towing light"},{colour:"white",label:"sternlight"}]}} caption="Towing vessel: two white masthead lights vertically, sidelights, a white sternlight, and a yellow towing light vertically above the sternlight."/><ul className="list-disc space-y-2 pl-5"><Requirement>Tow astern exceeding 200 m: three masthead lights vertically; towing vessel and ordinary tow each show a diamond where best seen. The ordinary vessel/object towed shows sidelights and a sternlight.</Requirement><Requirement>A rigid composite unit shows Rule 23 lights. Otherwise a pusher/tower alongside shows two vertical masthead lights, sidelights and sternlight; a vessel pushed ahead shows sidelights at its forward end, while a vessel towed alongside shows forward-end sidelights and a sternlight. Groups are lighted as one vessel.</Requirement><Requirement>A Rule 24(a) or (c) towing/pushing vessel also complies with Rule 23(a)(ii): the second masthead light abaft and higher is required at 50 m or more and optional under 50 m.</Requirement><Requirement>An inconspicuous partly submerged tow under 25 m breadth shows all-round white near each end (a dracone need not show the forward light); at 25 m breadth or more add lights at the breadth extremities. Over 100 m long, add lights so adjacent lights are no more than 100 m apart. Show a diamond near the after end and, if the tow exceeds 200 m, another as far forward as practicable.</Requirement><Requirement>Rule 24(h): if sufficient cause makes the tow's required lights/shapes impracticable, take all possible measures to light it or indicate its presence. Rule 24(i): a vessel not normally engaged in towing need not show Rule 24(a)/(c) towing-vessel lights when impracticably assisting a vessel in distress or otherwise needing help; indicate the relationship, particularly by illuminating the towline where practicable.</Requirement></ul></CardContent></Card>

    <Card id="rule-25" tabIndex={-1} className="scroll-mt-28 focus:outline-none"><CardHeader><CardTitle>Rule 25: sailing and oars</CardTitle></CardHeader><CardContent className="text-sm"><LightPlan title="Sailing vessel underway" height={[[{colour:"red",label:"optional all-round red at/near mast top"}],[{colour:"green",label:"optional all-round green below red"}],[{colour:"red",label:"port sidelight"},{colour:"green",label:"starboard sidelight"}],[{colour:"white",label:"sternlight"}]]} aspect={{ahead:[{colour:"red",label:"optional red over green all-round"},{colour:"red",label:"port sidelight"},{colour:"green",label:"starboard sidelight"}],port:[{colour:"red",label:"optional red over green all-round"},{colour:"red",label:"port sidelight"}],starboard:[{colour:"red",label:"optional red over green all-round"},{colour:"green",label:"starboard sidelight"}],astern:[{colour:"red",label:"optional red over green all-round"},{colour:"white",label:"sternlight"}]}} caption="Basic display: red port and green starboard sidelights plus white sternlight. Optional all-round red over green at/near the mast top remains visible all round and cannot be combined with the combined-lantern option."/><ul className="list-disc space-y-2 pl-5"><Requirement>Under 20 m may combine sidelights and sternlight in one lantern at or near the mast top where best seen—not a masthead light.</Requirement> <Requirement>Under 7 m, if practicable show the sailing lights; otherwise keep ready an electric torch or lit white lantern and show it in time. A vessel under oars may show sailing lights, otherwise the same ready white light.</Requirement><Requirement>A sailing vessel also propelled by machinery displays by day a cone, apex downward, forward where best seen.</Requirement></ul></CardContent></Card>

    <Card id="rule-26" tabIndex={-1} className="scroll-mt-28 focus:outline-none"><CardHeader><CardTitle>Rule 26: fishing vessels</CardTitle></CardHeader><CardContent className="text-sm"><LightPlan title="Trawling and making way" height={[[{colour:"white",label:"50 m+ masthead, abaft and higher than green"}],[{colour:"green",label:"all-round green"}],[{colour:"white",label:"all-round white"}],[{colour:"red",label:"port sidelight"},{colour:"green",label:"starboard sidelight"}],[{colour:"white",label:"sternlight"}]]} aspect={{ahead:[{colour:"green",label:"all-round green"},{colour:"white",label:"all-round white"},{colour:"red",label:"port"},{colour:"green",label:"starboard"}],astern:[{colour:"green",label:"all-round green"},{colour:"white",label:"all-round white"},{colour:"white",label:"sternlight"}]}} caption="Trawling status is all-round green over white. A trawler 50 m or more adds a white masthead light abaft and higher than the all-round green. When making way, add sidelights and sternlight."/><ul className="list-disc space-y-2 pl-5"><Requirement>Fishing other than trawling shows all-round red over white; both types show two cones apexes together by day and add sidelights/sternlight only when making way. A trawler under 50 m may show the additional masthead light.</Requirement><Requirement>Fishing other than trawling with gear extending over 150 m horizontally shows an all-round white at night or cone apex upward by day in the direction of the gear.</Requirement><Requirement>Rule 26(d) permits vessels fishing in close proximity to show Annex II signals in addition to Rule 26: a trawler shooting nets shows two all-round whites vertically; hauling nets shows all-round white over red; gear fast on an obstruction shows all-round red over white. Pair trawlers may direct searchlights forward toward each other. A purse seiner hampered by its gear may show two all-round yellows vertically flashing alternately every second with equal light/dark duration.</Requirement><Requirement>These signals apply only to vessels engaged in fishing as Rule 3 defines it—not vessels fishing with gear that does not restrict manoeuvrability.</Requirement></ul><p className="mt-3 text-xs"><strong>Memory aids:</strong> “green over white” and “red over white” can prompt recall; the requirements above, not the rhyme, control.</p></CardContent></Card>

    <Card id="rule-27" tabIndex={-1} className="scroll-mt-28 focus:outline-none"><CardHeader><CardTitle>Rule 27: NUC, RAM and operations</CardTitle></CardHeader><CardContent className="text-sm"><LightPlan title="RAM making way through the water" height={[[{colour:"red",label:"all-round red"}],[{colour:"white",label:"all-round white"}],[{colour:"red",label:"all-round red"}],[{colour:"white",label:"masthead light(s)"}],[{colour:"red",label:"port sidelight"},{colour:"green",label:"starboard sidelight"}],[{colour:"white",label:"sternlight"}]]} aspect={{ahead:[{colour:"red",label:"red–white–red status"},{colour:"white",label:"masthead light(s)"},{colour:"red",label:"port"},{colour:"green",label:"starboard"}],astern:[{colour:"red",label:"red–white–red status"},{colour:"white",label:"sternlight"}]}} caption="RAM status is three all-round lights red–white–red vertically. When making way through the water, add the applicable masthead light(s), sidelights and sternlight. NUC making way adds only sidelights and sternlight to its two all-round reds."/><ul className="list-disc space-y-2 pl-5"><Requirement>RAM making way through the water shows masthead light(s), sidelights and sternlight in addition to red-white-red. NUC making way adds sidelights and sternlight but no masthead-light requirement.</Requirement><Requirement>A RAM vessel at anchor also shows Rule 30 signals. RAM towing shows Rule 27 status plus Rule 24 towing lights/shapes. Dredging/underwater operations add two all-round reds or two balls on the obstructed side and two all-round greens or two diamonds on the safe-passing side; when at anchor this operation-specific display replaces Rule 30.</Requirement><Requirement>A diving vessel unable to show the full dredging display shows red-white-red, a rigid International Code flag A at least 1 m high, and measures for all-round visibility.</Requirement><Requirement>Mine-clearance: in addition to power-driven or anchor lights, three all-round green lights or three balls—one near the foremast head and one at each end of the fore yard—warn that it is dangerous to approach within 1,000 m.</Requirement></ul></CardContent></Card>

    <Card id="rule-28" tabIndex={-1} className="scroll-mt-28 focus:outline-none"><CardHeader><CardTitle>Rules 28–29: constrained by draught and pilot</CardTitle></CardHeader><CardContent className="text-sm"><LightPlan title="Constrained by draught underway" height={[[{colour:"red",label:"three all-round reds vertically"}],[{colour:"white",label:"Rule 23 masthead light(s)"}],[{colour:"red",label:"port sidelight"},{colour:"green",label:"starboard sidelight"}],[{colour:"white",label:"sternlight"}]]} aspect={{ahead:[{colour:"red",label:"three all-round reds"},{colour:"white",label:"masthead light(s)"},{colour:"red",label:"port"},{colour:"green",label:"starboard"}],astern:[{colour:"red",label:"three all-round reds"},{colour:"white",label:"sternlight"}]}} caption="A vessel constrained by draught may show three all-round red lights vertically, or a cylinder by day, in addition to the required Rule 23 power-driven display."/><ul className="list-disc space-y-2 pl-5"><Requirement>A pilot vessel engaged on pilotage duty shows all-round white over red at or near the masthead; when underway it also shows sidelights and sternlight; when at anchor it also shows Rule 30 anchor lights/shapes.</Requirement><Requirement>A pilot vessel not engaged on pilotage duty shows the lights/shapes prescribed for a similar vessel of its length.</Requirement></ul><p className="mt-3 text-xs"><strong>Memory aid:</strong> “white over red” is only a prompt; pilotage duty and the underway/anchor additions are essential.</p></CardContent></Card>

    <Card id="rule-30" tabIndex={-1} className="scroll-mt-28 focus:outline-none"><CardHeader><CardTitle>Rule 30: anchored and aground</CardTitle></CardHeader><CardContent className="text-sm"><LightPlan title="At anchor, 50 m or more" height={[[{colour:"white",label:"forward all-round white—higher"}],[{colour:"white",label:"aft all-round white—lower, at/near stern"}]]} aspect={{ahead:[{colour:"white",label:"forward all-round white"},{colour:"white",label:"aft all-round white"}],astern:[{colour:"white",label:"forward all-round white"},{colour:"white",label:"aft all-round white"}]}} caption="Forward all-round white and another all-round white at or near the stern, lower than the forward light. Under 50 m may show one all-round white where best seen."/><ul className="list-disc space-y-2 pl-5"><Requirement>At anchor show one ball forward where best seen. A vessel 100 m or more also uses available working/equivalent lights to illuminate decks; under 100 m may do so.</Requirement><Requirement>Aground shows anchor lights/shapes plus two all-round reds vertically and three balls vertically.</Requirement><Requirement>Under 7 m, when not in/near a narrow channel, fairway, anchorage or where vessels normally navigate, need not show anchor signals. Under 12 m aground need not show the two reds or three balls.</Requirement></ul></CardContent></Card>

    <Card id="rule-31" tabIndex={-1} className="scroll-mt-28 focus:outline-none"><CardHeader><CardTitle>Rule 31: seaplanes and WIG craft</CardTitle></CardHeader><CardContent className="text-sm"><ul className="list-disc space-y-2 pl-5"><Requirement>If a seaplane or WIG craft cannot exhibit lights and shapes with the prescribed characteristics or positions, it exhibits lights and shapes as closely similar in characteristics and position as possible.</Requirement></ul></CardContent></Card>
  </div>
  <aside className="rounded-md border p-4 text-sm"><strong>Reviewed scope and source version:</strong> educational summary of COLREG Part C, Rules 20–31, checked against the U.S. Coast Guard <a className="underline" href="https://www.navcen.uscg.gov/navigation-rules-amalgamated">Amalgamated Navigation Rules</a> and <a className="underline" href="https://www.navcen.uscg.gov/sites/default/files/pdf/navRules/Handbook/NavRules_Handbook_Corrected_08_08_2024.pdf">Navigation Rules and Regulations Handbook, corrected 8 August 2024</a>. It paraphrases requirements; consult the current rule text and Annex I for technical positioning/details. Mnemonics are explicitly labelled and have no legal force.</aside>
</div>;

export const PartCShapes = () => <div className="space-y-6"><p>Black day shapes indicate status; combinations and placement matter.</p><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
  <Card><CardContent className="pt-6"><ShapeStack shapes={["cone-down"]} caption="Cone, apex downward, forward where best seen: sailing vessel also propelled by machinery (Rule 25)." /></CardContent></Card>
  <Card><CardContent className="pt-6"><ShapeStack shapes={["diamond"]} caption="Diamond where best seen: tow exceeds 200 m; shown by towing vessel and tow (Rule 24)." /></CardContent></Card>
  <Card><CardContent className="pt-6"><ShapeStack shapes={["ball","ball"]} caption="Two balls vertically: vessel not under command (Rule 27)." /></CardContent></Card>
  <Card><CardContent className="pt-6"><ShapeStack shapes={["ball","diamond","ball"]} caption="Ball–diamond–ball vertically: vessel restricted in ability to manoeuvre (Rule 27)." /></CardContent></Card>
  <Card><CardContent className="pt-6"><ShapeStack shapes={["cylinder"]} caption="Cylinder: vessel constrained by draught may show it (Rule 28)." /></CardContent></Card>
  <Card id="rule-30" tabIndex={-1} className="scroll-mt-28 focus:outline-none"><CardContent className="pt-6"><h3 className="text-center font-bold">Ball</h3><ShapeStack shapes={["ball"]} caption="One ball forward: vessel at anchor (Rule 30)." /></CardContent></Card>
  <Card><CardContent className="pt-6"><ShapeStack shapes={["ball","ball","ball"]} caption="Three balls vertically: vessel aground, subject to the under-12 m exception (Rule 30)." /></CardContent></Card>
  <Card><CardContent className="pt-6"><ShapeStack shapes={["cone-down","cone-up"]} caption="Two cones with apexes together: vessel engaged in fishing (Rule 26)." /></CardContent></Card>
  <Card className="sm:col-span-2 lg:col-span-3"><CardContent className="pt-6"><h3 className="font-bold">Dredging / underwater operations</h3><DredgingShapePlan /></CardContent></Card>
</div><p className="text-sm text-muted-foreground">Operation-specific additions also apply: fishing gear over 150 m uses a cone apex upward toward the gear; mine-clearance uses three balls; pilot vessels at anchor add the anchor ball. See the corresponding rule cards under Lights for conditions.</p></div>;
