import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, Calculator, ChevronRight, Compass, TrendingUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { TOPIC_IDS } from "@/constants/topicRegistry";
import { TheoryCompletionButton } from "@/features/progress/TheoryCompletionButton";

const TidalHeightsTheory = () => {
  const navigate = useNavigate();
  const [heightAnswer, setHeightAnswer] = useState<"" | "3.9" | "4.2">("");
  const [timeAnswer, setTimeAnswer] = useState<"" | "both" | "one">("");
  const checksPassed = heightAnswer === "3.9" && timeAnswer === "both";

  return <div className="min-h-screen bg-background">
    <header className="sticky top-0 z-40 border-b bg-card/95 backdrop-blur-sm">
      <div className="container mx-auto flex items-center justify-between gap-4 px-4 py-4">
        <div className="flex min-w-0 items-center gap-3"><Button variant="ghost" size="icon" aria-label="Back to tides" onClick={() => navigate("/navigation/tides")}><ArrowLeft className="h-5 w-5" /></Button><div><h1 className="text-xl font-bold">Calculating Tidal Heights</h1><p className="text-sm text-muted-foreground">From published predictions to a conservative passage decision</p></div></div>
        <TheoryCompletionButton topicId={TOPIC_IDS.TIDES_HEIGHTS_THEORY} catalogueRevision="tides-heights-theory-v2" evidenceId="two-direction-curve-checks" evidenceSatisfied={checksPassed} lockedLabel="Pass both calculation checks" />
      </div>
    </header>

    <main className="container mx-auto max-w-5xl space-y-8 px-4 py-8">
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Compass className="h-5 w-5 text-blue-600" />Start with the publication</CardTitle></CardHeader><CardContent className="space-y-4 text-sm">
        <p>A <strong>standard port</strong> has its own daily HW/LW predictions and a labelled curve in the official almanac or tide tables. A <strong>secondary port</strong> is derived by applying the publication's time and height corrections to its named standard port. Do those corrections first; never copy a standard-port curve answer straight to a secondary port.</p>
        <div className="overflow-x-auto"><table className="w-full min-w-[34rem] border-collapse text-left"><caption className="mb-2 text-left font-semibold">Training extract — Northhaven standard port, 18 June (times in local zone; heights above CD)</caption><thead><tr className="bg-muted"><th className="border p-2">Date</th><th className="border p-2">LW</th><th className="border p-2">Height</th><th className="border p-2">HW</th><th className="border p-2">Height</th><th className="border p-2">LW</th><th className="border p-2">Height</th></tr></thead><tbody><tr><td className="border p-2">18 Jun</td><td className="border p-2">03:50</td><td className="border p-2">0.8 m</td><td className="border p-2">10:00</td><td className="border p-2">4.8 m</td><td className="border p-2">16:00</td><td className="border p-2">1.2 m</td></tr><tr><td className="border p-2">18/19 Jun</td><td className="border p-2">—</td><td className="border p-2">—</td><td className="border p-2">21:40</td><td className="border p-2">4.6 m</td><td className="border p-2">03:50 (+1 day)</td><td className="border p-2">0.8 m</td></tr></tbody></table></div>
        <p className="rounded-md border-l-4 border-amber-500 bg-amber-50 p-3 text-amber-950">Check the publication's date, time zone/DST note, units and datum. Predictions are astronomical: pressure, wind, river flow, swell and local effects can change both height and time. Compare with current gauge/harbour observations and notices.</p>
      </CardContent></Card>

      <Card><CardHeader><CardTitle className="flex items-center gap-2"><TrendingUp className="h-5 w-5 text-blue-600" />Use the standard-port curve</CardTitle><CardDescription>The publication's curve, not a generic sine wave, is the primary method.</CardDescription></CardHeader><CardContent className="space-y-5">
        <svg viewBox="0 0 720 270" role="img" aria-labelledby="curve-title curve-desc" className="h-auto w-full rounded-md border bg-slate-50"><title id="curve-title">Labelled standard-port tidal curve</title><desc id="curve-desc">A falling curve from high water at ten hundred and 4.8 metres to low water at sixteen hundred and 1.2 metres, crossing 3.9 metres at noon and 3 metres at thirteen hundred.</desc><line x1="70" y1="220" x2="680" y2="220" stroke="#334155"/><line x1="70" y1="30" x2="70" y2="220" stroke="#334155"/><text x="15" y="35" fontSize="14">HOT (m)</text><text x="625" y="255" fontSize="14">Time</text>{[1,2,3,4,5].map((h) => <g key={h}><line x1="65" y1={220-h*36} x2="680" y2={220-h*36} stroke="#cbd5e1"/><text x="48" y={225-h*36} fontSize="12">{h}</text></g>)}{[10,11,12,13,14,15,16].map((h,i) => <g key={h}><line x1={90+i*90} y1="220" x2={90+i*90} y2="225" stroke="#334155"/><text x={76+i*90} y="242" fontSize="12">{h}:00</text></g>)}<path d="M90 47 C170 50 225 70 270 80 S385 112 450 148 S560 177 630 177" fill="none" stroke="#2563eb" strokeWidth="4"/><circle cx="90" cy="47" r="5" fill="#2563eb"/><circle cx="630" cy="177" r="5" fill="#2563eb"/><line x1="270" y1="80" x2="270" y2="220" stroke="#059669" strokeDasharray="5 4"/><line x1="70" y1="80" x2="270" y2="80" stroke="#059669" strokeDasharray="5 4"/><text x="100" y="43" fontSize="13">HW 10:00, 4.8 m</text><text x="515" y="172" fontSize="13">LW 16:00, 1.2 m</text><text x="278" y="75" fontSize="13" fill="#047857">12:00 ≈ 3.9 m</text></svg>
        <ol className="list-decimal space-y-2 pl-5 text-sm"><li>Select the two <strong>adjacent</strong> events bracketing the required time: HW→LW is falling, LW→HW is rising. Write the date beside any time that crosses midnight.</li><li>Mark their published times and heights on the correct spring/neap curve sheet exactly as its instructions require.</li><li><strong>Height at time:</strong> enter at the requested clock time, move to the curve, then across through the height construction to read metres above CD.</li><li><strong>Time for height:</strong> convert the vessel/depth problem to required HOT, enter at that height, reverse the construction to the curve, then read the time. Search both adjacent limbs when both rising and falling answers matter.</li><li>Record source values, limb, units and result. Read only to the curve's resolution (normally about 0.1 m and 5–10 min), then apply a conservative margin—never imply false precision.</li></ol>
      </CardContent></Card>

      <div className="grid gap-6 lg:grid-cols-2">
        <Card><CardHeader><CardTitle>Worked 1: height at time</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p><strong>18 Jun, falling:</strong> HW 10:00 4.8 m; LW 16:00 1.2 m. At 12:00 the labelled curve reads <strong>HOT ≈ 3.9 m above CD</strong>.</p><p>At charted depth 1.4 m: water depth ≈ 1.4 + 3.9 = <strong>5.3 m</strong>. Over drying height 0.6 m (seabed above CD): depth ≈ 3.9 − 0.6 = <strong>3.3 m</strong>. Treating drying height as a negative charted depth gives the same arithmetic.</p><p>Quote 3.9 m, not 3.900 m. Reduce the planning value if uncertainty/current observations warrant it.</p></CardContent></Card>
        <Card><CardHeader><CardTitle>Worked 2: time(s) for height</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p>Draft 2.0 m + UKC 0.4 m over drying height 0.6 m requires HOT = 2.0 + 0.4 + 0.6 = <strong>3.0 m</strong>.</p><p>The curve gives about <strong>13:00 falling</strong>. On the following rising limb (LW 16:00 1.2 m to HW 22:00 4.8 m), it gives about <strong>19:00 rising</strong>: the usable window is approximately 13:00–19:00 before adding uncertainty and margin.</p><p><strong>Midnight discipline:</strong> for HW 18 Jun 21:40 4.6 m to LW 19 Jun 03:50 0.8 m, HOT 2.7 m occurs about <strong>19 Jun 00:45</strong>, not “18 Jun 00:45”.</p></CardContent></Card>
      </div>

      <Card><CardHeader><CardTitle>Datums, clearance and limits</CardTitle></CardHeader><CardContent className="grid gap-4 text-sm md:grid-cols-2"><div className="space-y-2"><p><strong>Under-keel:</strong> depth of water = charted depth + HOT; over a drying height, depth = HOT − drying height. Required HOT = draft + UKC − charted depth.</p><p><strong>Overhead:</strong> charted clearance is commonly referred to a high-water datum, not CD. Follow the chart/publication convention; compare available clearance with air draught plus margin. Do not combine values from different datums.</p></div><div className="space-y-2"><p>The <strong>Rule of Twelves</strong> (1, 2, 3, 3, 2, 1 twelfths per hour) is only a rough check for a fairly regular six-hour semidiurnal rise/fall. The equal 3rd and 4th hours are the maximum changes. Do not use it for strongly distorted, shallow-water or double high/low tides.</p><p>Standard-port predictions do not remove secondary-port corrections or weather/local uncertainty. If the margin matters, wait for more water, use observed levels and local advice, or do not proceed.</p></div></CardContent></Card>

      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Calculator className="h-5 w-5"/>Calculation checks</CardTitle></CardHeader><CardContent className="space-y-5 text-sm"><fieldset><legend className="font-semibold">1. On the worked falling limb, what HOT should be recorded at 12:00?</legend><label className="mr-6 inline-flex gap-2"><input type="radio" name="height-check" onChange={() => setHeightAnswer("3.9")}/>3.9 m above CD</label><label className="inline-flex gap-2"><input type="radio" name="height-check" onChange={() => setHeightAnswer("4.2")}/>4.2 m water depth</label>{heightAnswer && <p role="status" className="mt-2">{heightAnswer === "3.9" ? "Correct — enter at 12:00 and read about 3.9 m above CD; add charted depth separately." : "Try again — keep height of tide above CD separate from depth of water."}</p>}</fieldset><fieldset><legend className="font-semibold">2. Required HOT is 3.0 m and the passage spans LW. Which result is operationally complete?</legend><label className="mr-6 inline-flex gap-2"><input type="radio" name="time-check" onChange={() => setTimeAnswer("both")}/>13:00 falling and 19:00 rising, then apply margin</label><label className="inline-flex gap-2"><input type="radio" name="time-check" onChange={() => setTimeAnswer("one")}/>13:00 only</label>{timeAnswer && <p role="status" className="mt-2">{timeAnswer === "both" ? "Correct — reverse the construction on both limbs, identify direction, then narrow the window conservatively." : "Try again — a requested height can occur on both the falling and rising limbs."}</p>}</fieldset></CardContent></Card>

      <Card className="border-blue-200 bg-blue-50"><CardContent className="pt-6 text-sm"><strong>Practice-tool boundary:</strong> the planner is a learning aid using a smooth mathematical approximation. It is useful for rehearsing depth/clearance arithmetic and exploring windows, but it does not reproduce a named port's official curve, secondary-port corrections, weather or live observations. Recalculate from current official publications before navigation.</CardContent></Card>
      <div className="flex justify-center"><Button size="lg" onClick={() => navigate("/navigation/tides/heights-calc")} className="bg-emerald-600 hover:bg-emerald-700">Open the practice tool <ChevronRight className="ml-2 h-4 w-4"/></Button></div>
    </main>
  </div>;
};

export default TidalHeightsTheory;
